### ISSUE TITLE
Expected allele frequency is > 1 for some mutations

### ISSUE THREAD

**Issue by lbresadola** [TRON-Bioinformatics/vafator#40]
For some mutations the expected allele frequency (`eaf`) is > 1. This results in empty `pu` and `pw` fields.

**Comment by priesgo** [comment]
We found that this happens when having copy number values lower than 1. In particular in the formula below when the denominator becomes smaller than the numerator.

$f = \frac {\rho} {\rho * tumor\_CN + (1 - \rho) * normal\_ploidy}$ (1)

**Comment by priesgo** [comment]
This was fixed in release v2.1.0
