### ISSUE TITLE
The DP field counts doesn't match with counts in IGV

### ISSUE THREAD

**Issue by Rohit-Satyam** [TRON-Bioinformatics/vafator#42]
Hi @priesgo @martinloewer 

I have a VCF file generated from wf-artic pipeline that was ran on Minion ONT data of SARS-CoV 2 Samples. I tried using VAFATOR on it to assign VAF. However, I can see that the depth mentioned in `vafator_dp` filed is far high than what I can see in IGV. I was expecting this to be lower than IGV

```
MN908947.3	29510	.	A	C	26.51	PASS	DP=132;DPS=15,117;Pool=1;vafator_af=0.83571;vafator_ac=234;vafator_dp=280;vafator_eaf=0.5;vafator_pu=1;vafator_pw=1;vafator_k=5;vafator_bq=6,16;vafator_mq=60,60;vafator_pos=45.5,223.5;vafator_rsmq=-0.307;vafator_rsmq_pv=0.75859;vafator_rsbq=5.49;vafator_rsbq_pv=0;vafator_rspos=1.633;vafator_rspos_pv=0.10249	GT:GQ	1:27
```

![image](https://user-images.githubusercontent.com/55479480/201967404-b54d9f69-a012-4194-aaa7-368e4549d8ea.png)

**Comment by priesgo** [comment]
Can you please, let us know the quality thresholds you used for vafator and the vafator version?
Also, please, check any read filtering in IGV.


Thanks for the feedback!

**Comment by priesgo** [comment]
I just noticed 269 + 11 = 280... `IGV total counts + IGV dels = VAFator DP`
This observation holds in the example posted in https://github.com/nanoporetech/medaka/issues/395#issuecomment-1317829316

I am surprised though that the insertions are not counted. I need to investigate more on this issue.

**Comment by priesgo** [comment]
Right I think I understood this, or at least I have a hypothesis. 

VAFator uses pysam pileup on the mutation position, which returns all reads overlapping that position independently of the base supported or even if they actually contain a deletion overlapping that position. It may be counterintuitive, but I think deletions should be counted in the DP. Happy to hear different opinions.

Now, about insertions. If a read overlaps a given mutation, the overlap cannot be an insertion by definition. I suspect IGV is reporting insertions that start right after that particular position, but the supported base at the position under scrutiny would already be reported in the "normal" bases section. This could be confirmed by visual inspection in IGV.

**Comment by priesgo** [comment]
I'm closing this issue, feel free to reopen if needed.
