### ISSUE TITLE
VAFATOR doesn't assign VAF to a well know Trinucleotide-Bloc Mutation

### ISSUE THREAD

**Issue by Rohit-Satyam** [TRON-Bioinformatics/vafator#43]
Hi!!

I was wondering why VAFATOR assign the well known `28881–28883: GGG > AAC`  trinucleotide-bloc mutation (see [Paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9314171/)) with zero VAF even when there are so many reads aligning to this location. I observe this behavior for all the samples and it leads to my consensus assembly being tagged as `mediocre` or `bad` by Nextclade due to heavy penalty it put for `Reversions` (see [here](https://docs.nextstrain.org/projects/nextclade/en/stable/user/algorithm/07-quality-control.html))
  Attaching the BAM and variant file for your reference

![image](https://user-images.githubusercontent.com/55479480/202250277-e35b3c87-d809-4d65-ad4a-021a1b1ab5a9.png)

```
MN908947.3	28881	.	GGG	AAC	114.619	POOR_CALLS	DP=74;DPS=65,9;Pool=2;vafator_af=0;vafator_ac=0;vafator_dp=0;vafator_eaf=0.5;vafator_pu=1;vafator_pw=0;vafator_k=1;vafator_bq=0,0;vafator_mq=0,0;vafator_pos=0,0	GT:GQ	1:115
```
[sample1.vaf.zip](https://github.com/TRON-Bioinformatics/vafator/files/10024311/sample1.vaf.zip)
[sample1.primertrimmed.rg.sorted.zip](https://github.com/TRON-Bioinformatics/vafator/files/10024312/sample1.primertrimmed.rg.sorted.zip)

Note: The samples were processed using wf-artic pipeline and VAFator was used as follows:

```
vafator --input-vcf  ${vcf.toRealPath()} --output-vcf ${sid}.vaf.vcf --bam vafator ${bam.toRealPath()} --mapping-quality 0 --base-call-quality 0

bgzip -c ${sid}.vaf.vcf > ${sid}.vaf.vcf.gz
tabix -p vcf ${sid}.vaf.vcf.gz

## variant calls Tagging
bcftools view -Ob ${sid}.vaf.vcf.gz  | \
bcftools filter --exclude 'INFO/vafator_af < 0.5 && INFO/vafator_dp < 100 && INFO/vafator_ac < 50 ' \
--soft-filter POOR_CALLS --output-type v - | bcftools norm -d both - > ${sid}.vaf.annot.vcf

bgzip -c ${sid}.vaf.annot.vcf > ${sid}.vaf.annot.vcf.gz
tabix -p vcf ${sid}.vaf.annot.vcf.gz


## Finding the regions of low coverage
covtobed -x ${params.cov} ${bam.toRealPath()}  > ${sid}_lowcoverage.bed

## Building the Assembly, masking low coverage regions
bcftools consensus -f ${params.reference}  --include 'FILTER="PASS"' -m ${sid}_lowcoverage.bed --output ${sid}.fasta ${sid}.vaf.annot.vcf.gz

```

**Comment by priesgo** [comment]
MNVs are not yet supported by VAFator. It is maybe unconvenient, but if you split the MNVs into its constituent SNVs they will get annotated.

**Comment by Rohit-Satyam** [comment]
I tried decomposing MNVs. However the variant still has zero `DP`.

Code used can be found [here](https://github.com/Rohit-Satyam/wf-artic-utilities/blob/main/reviseAssembly.nf)


```
MN908947.3	28881	.	G	A	109.839	POOR_CALLS	DP=77;DPS=73,4;Pool=2;vafator_af=0;vafator_ac=0;vafator_dp=0;vafator_eaf=0.5;vafator_pu=1;vafator_pw=0;vafator_k=1;vafator_bq=0,0;vafator_mq=0,0;vafator_pos=0,0;OLD_CLUMPED=MN908947.3|28881|GGG|AAC|1	GT:GQ	1:110
MN908947.3	28882	.	G	A	109.839	POOR_CALLS	DP=77;DPS=73,4;Pool=2;vafator_af=0;vafator_ac=0;vafator_dp=0;vafator_eaf=0.5;vafator_pu=1;vafator_pw=0;vafator_k=1;vafator_bq=0,0;vafator_mq=0,0;vafator_pos=0,0;OLD_CLUMPED=MN908947.3|28881|GGG|AAC|1	GT:GQ	1:110
MN908947.3	28883	.	G	C	109.839	POOR_CALLS	DP=77;DPS=73,4;Pool=2;vafator_af=0;vafator_ac=0;vafator_dp=0;vafator_eaf=0.5;vafator_pu=1;vafator_pw=0;vafator_k=1;vafator_bq=0,0;vafator_mq=0,0;vafator_pos=0,0;OLD_CLUMPED=MN908947.3|28881|GGG|AAC|1	GT:GQ	1:110

```

**Comment by priesgo** [comment]
Checking your code I see that you decompose the MNVs after calling vafator, this needs to happen before.

**Comment by Rohit-Satyam** [comment]
My bad. Sorry for my ignorance. Thanks it works now!!

**Comment by priesgo** [comment]
Nice! Happy to help
